import { config } from 'dotenv'

config()

const ENV = process.env

// ACCESS
export const PORT = ENV.PORT || 3000
export const ACCESS_TOKEN = ENV.ACCESS_TOKEN
export const INTEGRATOR_ID = ENV.INTEGRATOR_ID
export const WEBSITE = ENV.WEBSITE

// TARJETA DE PAGO
export const VISA_NUM = ENV.VISA_NUM
export const VISA_CODE = ENV.VISA_CODE
export const VISA_DATE = ENV.VISA_DATE

// DATOS DEL PAGADOR O COMPRADOR
export const BUYER_NAME = ENV.BUYER_NAME
export const BUYER_LASTNAME = ENV.BUYER_LASTNAME
export const BUYER_AREA_CODE = ENV.BUYER_AREA_CODE
export const BUYER_PHONE = ENV.BUYER_PHONE
export const BUYER_STREET_NAME = ENV.BUYER_STREET_NAME
export const BUYER_STREET_NUMBER = ENV.BUYER_STREET_NUMBER
export const BUYER_ZIP_CODE = ENV.BUYER_ZIP_CODE
export const BUYER_EMAIL = ENV.BUYER_EMAIL

// DATOS DEL PRODUCTO DEMO
export const PRODUCT_ID = ENV.PRODUCT_ID
export const PRODUCT_DESCRIPTION = ENV.PRODUCT_DESCRIPTION
export const PRODUCT_QUANTITY = ENV.PRODUCT_QUANTITY
export const EXTERNAL_REFERENCE = ENV.EXTERNAL_REFERENCE